name: 'Code review'
description: 'Improved code review process'
author: David Ferlay

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  github-token:
    description: Your Github secret token to use API
    required: true

runs:
  using: node20
  main: dist/index.js
